server:
  port: 8760
spring:
  application:
    name: service
info:
  app:
    name: ${spring.application.name}
eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
